/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StringResponse } from '../../models/string-response';

export interface CreateChat$Params {

/**
 * The user id to create the chat with
 */
  'receiver-id': string;
}

export function createChat(http: HttpClient, rootUrl: string, params: CreateChat$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'headers'?: {

/**
 * Unique request identifier
 */
'requestId'?: string;

/**
 * Status code of the response
 */
'statusCode'?: string;
};
'body'?: StringResponse;
}>> {
  const rb = new RequestBuilder(rootUrl, createChat.PATH, 'post');
  if (params) {
    rb.query('receiver-id', params['receiver-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'headers'?: {
      
      /**
       * Unique request identifier
       */
      'requestId'?: string;
      
      /**
       * Status code of the response
       */
      'statusCode'?: string;
      };
      'body'?: StringResponse;
      }>;
    })
  );
}

createChat.PATH = '/api/v1/chats';
