/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BooleanResponse } from '../../models/boolean-response';
import { UserContactUpdateResource } from '../../models/user-contact-update-resource';

export interface UpdateContact$Params {
  'user-id': string;
      body: UserContactUpdateResource
}

export function updateContact(http: HttpClient, rootUrl: string, params: UpdateContact$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'headers'?: {

/**
 * Unique request identifier
 */
'requestId'?: string;

/**
 * Status code of the response
 */
'statusCode'?: string;
};
'body'?: BooleanResponse;
}>> {
  const rb = new RequestBuilder(rootUrl, updateContact.PATH, 'patch');
  if (params) {
    rb.path('user-id', params['user-id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'headers'?: {
      
      /**
       * Unique request identifier
       */
      'requestId'?: string;
      
      /**
       * Status code of the response
       */
      'statusCode'?: string;
      };
      'body'?: BooleanResponse;
      }>;
    })
  );
}

updateContact.PATH = '/api/v1/user-contacts/{user-id}/update-contact';
