services:
#  postgres:
#    container_name: postgres-sql-db
#    image: postgres
#    restart: unless-stopped
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      PGDATA: /var/lib/postgresql/data
#      POSTGRES_DB: whatsapp_clone
#    volumes:
#      - postgres:/data/postgres
#    ports:
#      - "5432:5432"
#    networks:
#      - whatsapp-clone

  mongo:
    container_name: mongo-db
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    ports:
      - "27017:27017"
    networks:
      - whatsapp-clone
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')" -u root -p password --authenticationDatabase admin
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s

  keycloak:
    container_name: keycloak-wc
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-file
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - whatsapp-clone
    command:
      - "start-dev"
      - "--import-realm"

volumes:
#  postgres:
#    driver: local
  mongo_data:
    driver: local
  mongo_config:
    driver: local
  keycloak_data:
    driver: local

networks:
  whatsapp-clone:
    driver: bridge
