services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.0-management
    restart: unless-stopped
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management UI
      - "61613:61613"    # STOMP
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
      - source: rabbitmq-config
        target: /etc/rabbitmq/rabbitmq.conf
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - whatsapp-clone

  redis-cache:
    container_name: redis-cache
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    command: [ "redis-server" ]
    networks:
      - whatsapp-clone

  mongo:
    container_name: mongo-db
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    ports:
      - "27017:27017"
    networks:
      - whatsapp-clone
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')" -u root -p password --authenticationDatabase admin
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s

  keycloak:
    container_name: keycloak-wc
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - "9090:8080"
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-file
      KEYCLOAK_HEALTH_ENABLED: "true"
    volumes:
      - keycloak_data:/opt/keycloak/data
    command:
      - "start-dev"
      - "--import-realm"
    networks:
      - whatsapp-clone

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management, rabbitmq_stomp]."

  rabbitmq-config:
    content: |
      loopback_users = none
      listeners.tcp.default = 5672
      default_pass = admin
      default_user = admin
      hipe_compile = false
      management.listener.port = 15672
      management.listener.ssl = false
      stomp.listeners.tcp.1 = 61613
      stomp.default_user = admin
      stomp.default_pass = admin

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
  mongo_data:
    driver: local
  mongo_config:
    driver: local
  keycloak_data:
    driver: local
  redis_data:
    driver: local

networks:
  whatsapp-clone:
    driver: bridge
