/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MobileNumber {

  /**
   * The phone country code
   */
  countryCode?: string;

  /**
   * The phone number
   */
  phoneNumber?: string;
}
