/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MobileNumber } from '../models/mobile-number';
import { StoryDetailsResponse } from '../models/story-details-response';
export interface UserResponse {

  /**
   * The user email
   */
  email?: string;

  /**
   * The user firstname
   */
  firstName?: string;

  /**
   * The user Id
   */
  id?: string;

  /**
   * The user lastname
   */
  lastName?: string;

  /**
   * The last time when the user was online
   */
  lastSeen?: string;
  mobileNumber?: MobileNumber;
  online?: boolean;

  /**
   * The user profile image reference
   */
  profilePictureReference?: string;

  /**
   * The stories list
   */
  stories?: Array<StoryDetailsResponse>;
}
