/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Schema to hold the user contact update data
 */
export interface UserContactUpdateResource {

  /**
   * The contact fullName
   */
  fullName: string;
}
