/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MobileNumber } from '../models/mobile-number';

/**
 * Schema to hold the user details update data
 */
export interface UserUpdateResource {

  /**
   * The user about section
   */
  description?: string;

  /**
   * The user firstname
   */
  firstName?: string;

  /**
   * The user lastname
   */
  lastName?: string;
  mobileNumber?: MobileNumber;

  /**
   * The user profile image (only image files allowed)
   */
  profilePicture?: Blob;
}
