/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Schema to hold the user contact creation data
 */
export interface UserContactCreationResource {

  /**
   * The user email
   */
  email: string;

  /**
   * The contact firstname
   */
  firstname?: string;

  /**
   * Flag for favourite contacts
   */
  isFavourite?: boolean;

  /**
   * The contact lastname
   */
  lastname?: string;
}
