/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BooleanResponse } from '../../models/boolean-response';

export interface DeleteMedia$Params {
  reference: string;
}

export function deleteMedia(http: HttpClient, rootUrl: string, params: DeleteMedia$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'headers'?: {

/**
 * Unique request identifier
 */
'requestId'?: any;

/**
 * Status code of the response
 */
'statusCode'?: any;
};
'body'?: BooleanResponse;
}>> {
  const rb = new RequestBuilder(rootUrl, deleteMedia.PATH, 'delete');
  if (params) {
    rb.path('reference', params.reference, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'headers'?: {
      
      /**
       * Unique request identifier
       */
      'requestId'?: any;
      
      /**
       * Status code of the response
       */
      'statusCode'?: any;
      };
      'body'?: BooleanResponse;
      }>;
    })
  );
}

deleteMedia.PATH = '/api/v1/media/{reference}';
