/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MediaReferenceListResponse } from '../../models/media-reference-list-response';

export interface GetMediaListReferences$Params {
  entityId: string;
}

export function getMediaListReferences(http: HttpClient, rootUrl: string, params: GetMediaListReferences$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'headers'?: {

/**
 * Unique request identifier
 */
'requestId'?: any;

/**
 * Status code of the response
 */
'statusCode'?: any;
};
'body'?: MediaReferenceListResponse;
}>> {
  const rb = new RequestBuilder(rootUrl, getMediaListReferences.PATH, 'get');
  if (params) {
    rb.path('entityId', params.entityId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'headers'?: {
      
      /**
       * Unique request identifier
       */
      'requestId'?: any;
      
      /**
       * Status code of the response
       */
      'statusCode'?: any;
      };
      'body'?: MediaReferenceListResponse;
      }>;
    })
  );
}

getMediaListReferences.PATH = '/api/v1/media/list/{entityId}';
