/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Schema to hold the chat-user update data
 */
export interface ChatUserUpdateResource {

  /**
   * The chat user update operation
   */
  operation: 'ADD_NEW_USER' | 'REMOVE_EXISTING_USER' | 'MODIFY_EXISTING_USER_ROLE';

  /**
   * The user account Id
   */
  userId: string;

  /**
   * The user role in the chat [Mandatory in case operation=MODIFY_EXISTING_USER_ROLE]
   */
  userRole?: 'CREATOR' | 'ADMIN' | 'MEMBER';
}
