/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MessageResponse } from '../models/message-response';

/**
 * Schema to hold the chat messages response
 */
export interface ChatMessageResponse {
  [key: string]: Array<MessageResponse>;
}
