/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Schema to hold the chat user response
 */
export interface ChatUserResponse {
  admin?: boolean;

  /**
   * The user fullname
   */
  fullname?: string;

  /**
   * The user Id
   */
  id?: string;

  /**
   * The user profile image reference
   */
  imageFileReference?: string;
}
