/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Schema to hold the group chat update data
 */
export interface GroupChatUpdateResource {

  /**
   * The group chat profile image (only image files allowed)
   */
  chatImage?: Blob;

  /**
   * The bio of the group chat
   */
  description?: string;

  /**
   * The group chat name
   */
  name?: string;
}
