/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Schema to hold the group chat creation data
 */
export interface GroupChatCreationResource {

  /**
   * The bio of the group chat
   */
  description?: string;

  /**
   * The group chat profile image (only image files allowed)
   */
  file?: Blob;

  /**
   * The group chat name
   */
  name: string;

  /**
   * List of user accounts Ids to be added in the group chat
   */
  receiversIds?: Array<string>;
}
