import {RepliedMessage} from './replied-message';
/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Schema to hold the message response
 */
export interface MessageResponse {

  /**
   * The message string content
   */
  content?: string;

  /**
   * The message creation time
   */
  createdAt?: string;
  forwarded?: boolean;

  /**
   * The message id
   */
  id?: number;

  /**
   * The message media list references
   */
  mediaListReferences?: Array<string>;
  repliedMessage?: RepliedMessage;

  /**
   * The creator user id
   */
  senderId?: string;

  /**
   * The message state
   */
  state?: 'SENT' | 'RECEIVED' | 'SEEN';

  /**
   * The message content type
   */
  type?: 'TEXT' | 'MEDIA' | 'AUDIO';
}
