/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Schema to hold the message update data
 */
export interface MessageUpdateResource {

  /**
   * The message string content
   */
  content: string;
}
