/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Schema to hold the message creation response
 */
export interface MessageCreationResponse {

  /**
   * The message id
   */
  id?: number;

  /**
   * The message media list references
   */
  mediaListReferences?: Array<string>;
}
