/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MessageContent } from '../models/message-content';
export interface RepliedMessage {

  /**
   * The message string content
   */
  content?: MessageContent;

  /**
   * The source replying message id
   */
  id?: number;

  /**
   * The message content type
   */
  messageType?: 'TEXT' | 'MEDIA' | 'AUDIO';
}
