/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Schema to hold the starred message response
 */
export interface StarredMessageResponse {

  /**
   * The message string content
   */
  content?: string;

  /**
   * The message creation time
   */
  createdAt?: string;

  /**
   * The message id
   */
  id?: number;

  /**
   * The message media list references
   */
  mediaListReferences?: Array<string>;

  /**
   * The creator user id
   */
  senderId?: string;

  /**
   * The message content type
   */
  type?: 'TEXT' | 'MEDIA' | 'AUDIO';
}
