/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Schema to hold the string response
 */
export interface StringResponse {

  /**
   * Response string content
   */
  content?: string;
}
