/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ChatResponse } from '../models/chat-response';
import { createChat } from '../fn/chat-controller/create-chat';
import { CreateChat$Params } from '../fn/chat-controller/create-chat';
import { createGroupChat } from '../fn/chat-controller/create-group-chat';
import { CreateGroupChat$Params } from '../fn/chat-controller/create-group-chat';
import { getChatsByUser } from '../fn/chat-controller/get-chats-by-user';
import { GetChatsByUser$Params } from '../fn/chat-controller/get-chats-by-user';
import { StringResponse } from '../models/string-response';

@Injectable({ providedIn: 'root' })
export class ChatControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getChatsByUser()` */
  static readonly GetChatsByUserPath = '/api/v1/chats';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getChatsByUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  getChatsByUser$Response(params?: GetChatsByUser$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ChatResponse>>> {
    return getChatsByUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getChatsByUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getChatsByUser(params?: GetChatsByUser$Params, context?: HttpContext): Observable<Array<ChatResponse>> {
    return this.getChatsByUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ChatResponse>>): Array<ChatResponse> => r.body)
    );
  }

  /** Path part for operation `createChat()` */
  static readonly CreateChatPath = '/api/v1/chats';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createChat()` instead.
   *
   * This method doesn't expect any request body.
   */
  createChat$Response(params: CreateChat$Params, context?: HttpContext): Observable<StrictHttpResponse<StringResponse>> {
    return createChat(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createChat$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  createChat(params: CreateChat$Params, context?: HttpContext): Observable<StringResponse> {
    return this.createChat$Response(params, context).pipe(
      map((r: StrictHttpResponse<StringResponse>): StringResponse => r.body)
    );
  }

  /** Path part for operation `createGroupChat()` */
  static readonly CreateGroupChatPath = '/api/v1/chats/group';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createGroupChat()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createGroupChat$Response(params: CreateGroupChat$Params, context?: HttpContext): Observable<StrictHttpResponse<StringResponse>> {
    return createGroupChat(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createGroupChat$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createGroupChat(params: CreateGroupChat$Params, context?: HttpContext): Observable<StringResponse> {
    return this.createGroupChat$Response(params, context).pipe(
      map((r: StrictHttpResponse<StringResponse>): StringResponse => r.body)
    );
  }

}
