/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Schema to hold the media list response
 */
export interface MediaReferenceListResponse {

  /**
   * The entity media list references
   */
  mediaReferencesList?: Array<string>;
}
