spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8071
  profiles:
    active: default
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            websocket:
              proxy-ping: true
          global-filter:
            websocket-routing:
              enabled: true
