services:
  network-deploy-service:
    networks:
      - whatsapp-clone

  microservice-base:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  config-server-deploy-base:
    extends:
      service: microservice-base
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071/"
      SPRING_PROFILES_ACTIVE: "default"

  eureka-server-deploy-base:
    extends:
      service: config-server-deploy-base
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080/actuator/health/readiness" ]
      start_period: 10s
      retries: 10
      interval: 10s
      timeout: 5s
    environment:
      SERVER_PORT: 8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8090/eureka/"
      EUREKA_INSTANCE_HOSTNAME: "eureka-server"
      EUREKA_INSTANCE_PREFERIPADDRESS: false

  mongo-db-deploy-base:
    extends:
      service: eureka-server-deploy-base
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      SPRING_DATA_MONGODB_HOST: mongo

  cache-deploy-base:
    extends:
      service: mongo-db-deploy-base
    depends_on:
      redis-cache:
        condition: service_healthy
    environment:
      SPRING_DATA_REDIS_HOST: redis-cache
