/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { BooleanResponse } from './models/boolean-response';
export type { ErrorBody } from './models/error-body';
export type { MediaReferenceListResponse } from './models/media-reference-list-response';
