/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MediaUploadResource } from '../models/media-upload-resource';
export interface MessageResource {
  chatId?: string;
  content?: string;
  forwarded?: boolean;
  mediaResources?: Array<MediaUploadResource>;
  messageType?: 'TEXT' | 'MEDIA' | 'AUDIO';
  repliedMessageId?: number;
  senderId?: string;
}
