spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:http://localhost:8071
  profiles:
    active: default

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: "${spring.application.name}"
