spring:
  main:
    web-application-type: servlet
  cache:
    type: redis
  data:
    mongodb:
      host: localhost
      port: 27017
      database: whatsapp-clone
      username: root
      password: password
      authentication-database: admin
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2s
  grpc:
    server:
      port: 9091
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  servlet:
    multipart:
      max-file-size: 100MB

server:
  port: 8091

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8090/eureka/"

chats:
  page:
    max-messages-size: 20

media:
  service:
    grpc:
      host: localhost
      port: 9092
      enabled: false

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
