spring:
  main:
    web-application-type: servlet
  cache:
    type: redis
  data:
    mongodb:
      host: localhost
      port: 27017
      database: whatsapp-clone
      username: root
      password: password
      authentication-database: admin
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2s

server:
  port: 8094

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8090/eureka/"
