server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8090/eureka/"

spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/whatsapp-clone"
          jwk-set-uri: "http://localhost:9090/realms/whatsapp-clone/protocol/openid-connect/certs"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: whatsapp-clone
      username: root
      password: password
      authentication-database: admin
      auto-index-creation: true

springdoc:
  swagger-ui:
    urls:
      - name: Core
        url: /core/v3/api-docs
      - name: Media
        url: /media/v3/api-docs
