spring:
  main:
    web-application-type: reactive
  webflux:
    multipart:
      max-file-size: 50MB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: whatsapp-clone
      username: root
      password: password
      authentication-database: admin
      auto-index-creation: true

server:
  port: 8092

application:
  file:
    uploads:
      media-soft-delete: false
      media-storage-type: local
      media-output-path: ./uploads
      cloudinary-media-path: Whatsapp_clone

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8090/eureka/"
