spring:
  main:
    web-application-type: servlet
  data:
    mongodb:
      host: localhost
      port: 27017
      database: whatsapp-clone
      username: root
      password: password
      authentication-database: admin
      auto-index-creation: true
  grpc:
    server:
      port: 9093

server:
  port: 8093

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8090/eureka/"

media:
  service:
    grpc:
      host: localhost
      port: 9092
      enabled: true
  hard-delete-flag: true
