/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StoryCreationResource } from '../../models/story-creation-resource';
import { StringResponse } from '../../models/string-response';

export interface CreateStory$Params {
      body: StoryCreationResource
}

export function createStory(http: HttpClient, rootUrl: string, params: CreateStory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StringResponse>>> {
  const rb = new RequestBuilder(rootUrl, createStory.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<StringResponse>>;
    })
  );
}

createStory.PATH = '/api/v1/user-stories';
