/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StoryDetailsResponse } from '../../models/story-details-response';

export interface GetMyContactsStories$Params {
}

export function getMyContactsStories(http: HttpClient, rootUrl: string, params?: GetMyContactsStories$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: Array<StoryDetailsResponse>;
}>> {
  const rb = new RequestBuilder(rootUrl, getMyContactsStories.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      [key: string]: Array<StoryDetailsResponse>;
      }>;
    })
  );
}

getMyContactsStories.PATH = '/api/v1/user-stories/contacts';
