/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserStoriesListResponse } from '../../models/user-stories-list-response';

export interface GetMyStories$Params {
}

export function getMyStories(http: HttpClient, rootUrl: string, params?: GetMyStories$Params, context?: HttpContext): Observable<StrictHttpResponse<UserStoriesListResponse>> {
  const rb = new RequestBuilder(rootUrl, getMyStories.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserStoriesListResponse>;
    })
  );
}

getMyStories.PATH = '/api/v1/user-stories/me';
