spring:
  application:
    name: whatsapp-clone-api
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/whatsapp_clone
    username: postgres
    password: postgres
  flyway:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:9090/realms/whatsapp-clone/protocol/openid-connect/certs"
  servlet:
    multipart:
      max-file-size: 50MB

application:
  file:
    uploads:
      media-output-path: ./uploads
