/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Schema to hold the story details response
 */
export interface StoryDetailsResponse {

  /**
   * The story string content
   */
  content?: string;

  /**
   * The story creation date
   */
  createdAt?: string;

  /**
   * The story id
   */
  id?: number;

  /**
   * The story media reference
   */
  mediaReference?: string;

  /**
   * The story type
   */
  storyType?: 'TEXT' | 'MEDIA';
}
