/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Schema to hold the story update data
 */
export interface StoryUpdateResource {

  /**
   * The story string content
   */
  content: string;
}
