/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Schema to hold the story creation data
 */
export interface StoryCreationResource {

  /**
   * The story string content
   */
  content?: string;

  /**
   * The story media file content
   */
  file?: Blob;
}
