/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StoryDetailsResponse } from '../models/story-details-response';

/**
 * Schema to hold the story details response data
 */
export interface UserStoriesListResponse {
  storiesList?: Array<StoryDetailsResponse>;
}
