server:
  port: 8071

spring:
  application:
    name: config-service
  profiles:
    active: native

  cloud:
    config:
      server:
    #        git:
    #          uri: ""
    #          default-label: "master"
    #          timeout: 5
    #          clone-on-start: true
    #          force-pull: true
        native:
          search-locations: "file:///E://Coding//Spring Projects//Whatsapp Clone//configurations"

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

encrypt:
  key: ${ENCRYPTION_KEY}
