import {faCheckSquare, faCopy, faStar, faTimesCircle, IconDefinition} from '@fortawesome/free-regular-svg-icons';
import {
  faAdd,
  faArrowLeft, faCamera,
  faCheck,
  faEllipsisVertical,
  faFaceLaugh,
  faFilter,
  faHeadphones,
  faImage,
  faPaperPlane, faPenToSquare,
  faSearch,
  faUser,
  faUserGroup,
  faVideo,
  faPhone, faPaperclip, faMicrophone, faFile, faPollH, faCalendar, faPaintbrush, faReply, faShare, faThumbTack, faTrash,
  faShareSquare, faTimes, faRightToBracket
} from '@fortawesome/free-solid-svg-icons';
import {
  faUser as farUser,
  faFaceSmile as farFaceSmile,
} from '@fortawesome/free-regular-svg-icons';

export const fontAwesomeIcons: IconDefinition[] = [
  faAdd,
  faFilter,
  faPenToSquare,
  faArrowLeft,
  faCheck,
  faEllipsisVertical,
  faFaceLaugh,
  faPaperclip,
  faHeadphones,
  faImage,
  faPaperPlane,
  faSearch,
  farUser,
  faUser,
  faUserGroup,
  faVideo,
  faUserGroup,
  faCamera,
  farFaceSmile,
  faPhone,
  faMicrophone,
  faFile,
  faPollH,
  faCalendar,
  faPaintbrush,
  faReply,
  faCopy,
  faShare,
  faStar,
  faThumbTack,
  faTrash,
  faShareSquare,
  faCheckSquare,
  faTimesCircle,
  faRightToBracket
]
